const Courses = [
  {
    id: 1,
    data: {
      name: "Scratch Programming Language",
      short: "Scratch",
      about:
        "Scratch is a beginner-friendly visual programming language and platform developed by the MIT Media Lab.",
      levels: "2",
      hours: "16",
      imgName: "scratch c.jpg",
      course_info: {
        info: "In recent years, Virtual Reality (VR) has transitioned from a futuristic concept into a tangible and transformative technology that is changing the way we interact with the digital world. This article delves into the world of VR, exploring its origins, current applications, and the exciting possibilities it holds for the future.",
        Understanding:
          "Virtual Reality Virtual Reality refers to a simulated experience that can be similar to or entirely different from the real world. It is typically generated by computer technology and experienced through sensory perceptions such as sight, sound, touch, and even smell in some advanced systems. The primary goal of VR is to immerse users in a synthetic environment, blurring the line between what is real and what is computer-generated.",
        A_Brief_History: `The concept of VR has been around for decades, with early experiments dating back to the 1960s. However, it wasn't until the 21st century that VR technology began to gain significant traction. Key milestones include the development of the Oculus Rift headset in 2012 and the subsequent acquisition of Oculus by Facebook (now Meta) in 2014, which injected substantial resources into VR development.`,
        The_Future: `The future of VR is bright, with ongoing advancements in hardware and software pushing the boundaries of what is possible `,
        Conclusion: `Virtual Reality is no longer science fiction; it's a transformative technology with a growing impact on our lives. As VR continues to evolve, it will touch virtually every aspect of our daily routines, from entertainment and education to healthcare and beyond. As we journey deeper into this immersive world, one thing is clear: Virtual Reality is here to stay, and the possibilities are virtually endless.`,
      },
    },
  },
  {
    id: 2,
    data: {
      name: "Python Programming Language",
      short: "Python",
      about:
        "Python is a high-level, general-purpose programming language.Python is dynamically typed and garbage-collected.",
      levels: "4",
      hours: "32",
      imgName: "python.jpg",
      course_info: {
        info: "In recent years, Virtual Reality (VR) has transitioned from a futuristic concept into a tangible and transformative technology that is changing the way we interact with the digital world. This article delves into the world of VR, exploring its origins, current applications, and the exciting possibilities it holds for the future.",
        Understanding:
          "Virtual Reality Virtual Reality refers to a simulated experience that can be similar to or entirely different from the real world. It is typically generated by computer technology and experienced through sensory perceptions such as sight, sound, touch, and even smell in some advanced systems. The primary goal of VR is to immerse users in a synthetic environment, blurring the line between what is real and what is computer-generated.",
        A_Brief_History: `The concept of VR has been around for decades, with early experiments dating back to the 1960s. However, it wasn't until the 21st century that VR technology began to gain significant traction. Key milestones include the development of the Oculus Rift headset in 2012 and the subsequent acquisition of Oculus by Facebook (now Meta) in 2014, which injected substantial resources into VR development.`,
        The_Future: `The future of VR is bright, with ongoing advancements in hardware and software pushing the boundaries of what is possible `,
        Conclusion: `Virtual Reality is no longer science fiction; it's a transformative technology with a growing impact on our lives. As VR continues to evolve, it will touch virtually every aspect of our daily routines, from entertainment and education to healthcare and beyond. As we journey deeper into this immersive world, one thing is clear: Virtual Reality is here to stay, and the possibilities are virtually endless.`,
      },
    },
  },
  {
    id: 3,
    data: {
      name: "Artificial Intelligence (AI)",
      short: "AI",
      about:
        "Artificial Intelligence (AI) refers to the simulation of human intelligence in machines or computer programs.",
      levels: "2",
      hours: "16",
      imgName: "ai.jpg",
      course_info: {
        info: "In recent years, Virtual Reality (VR) has transitioned from a futuristic concept into a tangible and transformative technology that is changing the way we interact with the digital world. This article delves into the world of VR, exploring its origins, current applications, and the exciting possibilities it holds for the future.",
        Understanding:
          "Virtual Reality Virtual Reality refers to a simulated experience that can be similar to or entirely different from the real world. It is typically generated by computer technology and experienced through sensory perceptions such as sight, sound, touch, and even smell in some advanced systems. The primary goal of VR is to immerse users in a synthetic environment, blurring the line between what is real and what is computer-generated.",
        A_Brief_History: `The concept of VR has been around for decades, with early experiments dating back to the 1960s. However, it wasn't until the 21st century that VR technology began to gain significant traction. Key milestones include the development of the Oculus Rift headset in 2012 and the subsequent acquisition of Oculus by Facebook (now Meta) in 2014, which injected substantial resources into VR development.`,
        The_Future: `The future of VR is bright, with ongoing advancements in hardware and software pushing the boundaries of what is possible `,
        Conclusion: `Virtual Reality is no longer science fiction; it's a transformative technology with a growing impact on our lives. As VR continues to evolve, it will touch virtually every aspect of our daily routines, from entertainment and education to healthcare and beyond. As we journey deeper into this immersive world, one thing is clear: Virtual Reality is here to stay, and the possibilities are virtually endless.`,
      },
    },
  },
  {
    id: 4,
    data: {
      name: "Machine Learning",
      short: "Machine Learning",
      about:
        "subset of AI that focuses on the development of algorithms that allow computers to learn and improve from experience.",
      levels: "2",
      hours: "16",
      imgName: "ml.jpg",
      course_info: {
        info: "In recent years, Virtual Reality (VR) has transitioned from a futuristic concept into a tangible and transformative technology that is changing the way we interact with the digital world. This article delves into the world of VR, exploring its origins, current applications, and the exciting possibilities it holds for the future.",
        Understanding:
          "Virtual Reality Virtual Reality refers to a simulated experience that can be similar to or entirely different from the real world. It is typically generated by computer technology and experienced through sensory perceptions such as sight, sound, touch, and even smell in some advanced systems. The primary goal of VR is to immerse users in a synthetic environment, blurring the line between what is real and what is computer-generated.",
        A_Brief_History: `The concept of VR has been around for decades, with early experiments dating back to the 1960s. However, it wasn't until the 21st century that VR technology began to gain significant traction. Key milestones include the development of the Oculus Rift headset in 2012 and the subsequent acquisition of Oculus by Facebook (now Meta) in 2014, which injected substantial resources into VR development.`,
        The_Future: `The future of VR is bright, with ongoing advancements in hardware and software pushing the boundaries of what is possible `,
        Conclusion: `Virtual Reality is no longer science fiction; it's a transformative technology with a growing impact on our lives. As VR continues to evolve, it will touch virtually every aspect of our daily routines, from entertainment and education to healthcare and beyond. As we journey deeper into this immersive world, one thing is clear: Virtual Reality is here to stay, and the possibilities are virtually endless.`,
      },
    },
  },
  {
    id: 5,
    data: {
      name: "Deep Learning",
      short: "Deep Learning",
      about:
        "subfield of machine learning that uses artificial neural networks to model and solve complex problems.",
      levels: "2",
      hours: "16",
      imgName: "DL.jpg",
      course_info: {
        info: "In recent years, Virtual Reality (VR) has transitioned from a futuristic concept into a tangible and transformative technology that is changing the way we interact with the digital world. This article delves into the world of VR, exploring its origins, current applications, and the exciting possibilities it holds for the future.",
        Understanding:
          "Virtual Reality Virtual Reality refers to a simulated experience that can be similar to or entirely different from the real world. It is typically generated by computer technology and experienced through sensory perceptions such as sight, sound, touch, and even smell in some advanced systems. The primary goal of VR is to immerse users in a synthetic environment, blurring the line between what is real and what is computer-generated.",
        A_Brief_History: `The concept of VR has been around for decades, with early experiments dating back to the 1960s. However, it wasn't until the 21st century that VR technology began to gain significant traction. Key milestones include the development of the Oculus Rift headset in 2012 and the subsequent acquisition of Oculus by Facebook (now Meta) in 2014, which injected substantial resources into VR development.`,
        The_Future: `The future of VR is bright, with ongoing advancements in hardware and software pushing the boundaries of what is possible `,
        Conclusion: `Virtual Reality is no longer science fiction; it's a transformative technology with a growing impact on our lives. As VR continues to evolve, it will touch virtually every aspect of our daily routines, from entertainment and education to healthcare and beyond. As we journey deeper into this immersive world, one thing is clear: Virtual Reality is here to stay, and the possibilities are virtually endless.`,
      },
    },
  },
  {
    id: 6,
    data: {
      name: "Natural Language Processing (NLP)",
      short: "NLP",
      about:
        "NLP is a branch of AI that deals with the interaction between computers and human language.",
      levels: "2",
      hours: "16",
      imgName: "NLP.jpg",
      course_info: {
        info: "In recent years, Virtual Reality (VR) has transitioned from a futuristic concept into a tangible and transformative technology that is changing the way we interact with the digital world. This article delves into the world of VR, exploring its origins, current applications, and the exciting possibilities it holds for the future.",
        Understanding:
          "Virtual Reality Virtual Reality refers to a simulated experience that can be similar to or entirely different from the real world. It is typically generated by computer technology and experienced through sensory perceptions such as sight, sound, touch, and even smell in some advanced systems. The primary goal of VR is to immerse users in a synthetic environment, blurring the line between what is real and what is computer-generated.",
        A_Brief_History: `The concept of VR has been around for decades, with early experiments dating back to the 1960s. However, it wasn't until the 21st century that VR technology began to gain significant traction. Key milestones include the development of the Oculus Rift headset in 2012 and the subsequent acquisition of Oculus by Facebook (now Meta) in 2014, which injected substantial resources into VR development.`,
        The_Future: `The future of VR is bright, with ongoing advancements in hardware and software pushing the boundaries of what is possible `,
        Conclusion: `Virtual Reality is no longer science fiction; it's a transformative technology with a growing impact on our lives. As VR continues to evolve, it will touch virtually every aspect of our daily routines, from entertainment and education to healthcare and beyond. As we journey deeper into this immersive world, one thing is clear: Virtual Reality is here to stay, and the possibilities are virtually endless.`,
      },
    },
  },
  {
    id: 7,
    data: {
      name: "Roblox Kids Programming",
      short: "Roblox",
      about:
        "Roblox offers a platform that allows users, including kids, to create and play games.",
      levels: "2",
      hours: "16",
      imgName: "Roblox-China.jpg",
      course_info: {
        info: "In recent years, Virtual Reality (VR) has transitioned from a futuristic concept into a tangible and transformative technology that is changing the way we interact with the digital world. This article delves into the world of VR, exploring its origins, current applications, and the exciting possibilities it holds for the future.",
        Understanding:
          "Virtual Reality Virtual Reality refers to a simulated experience that can be similar to or entirely different from the real world. It is typically generated by computer technology and experienced through sensory perceptions such as sight, sound, touch, and even smell in some advanced systems. The primary goal of VR is to immerse users in a synthetic environment, blurring the line between what is real and what is computer-generated.",
        A_Brief_History: `The concept of VR has been around for decades, with early experiments dating back to the 1960s. However, it wasn't until the 21st century that VR technology began to gain significant traction. Key milestones include the development of the Oculus Rift headset in 2012 and the subsequent acquisition of Oculus by Facebook (now Meta) in 2014, which injected substantial resources into VR development.`,
        The_Future: `The future of VR is bright, with ongoing advancements in hardware and software pushing the boundaries of what is possible `,
        Conclusion: `Virtual Reality is no longer science fiction; it's a transformative technology with a growing impact on our lives. As VR continues to evolve, it will touch virtually every aspect of our daily routines, from entertainment and education to healthcare and beyond. As we journey deeper into this immersive world, one thing is clear: Virtual Reality is here to stay, and the possibilities are virtually endless.`,
      },
    },
  },
  {
    id: 8,
    data: {
      name: "Virtual Reality (VR)",
      short: "VR",
      about:
        "can be an exciting and educational technology for kids when used responsibly.",
      levels: "2",
      hours: "16",
      imgName: "vr.jpg",
      course_info: {
        info: "In recent years, Virtual Reality (VR) has transitioned from a futuristic concept into a tangible and transformative technology that is changing the way we interact with the digital world. This article delves into the world of VR, exploring its origins, current applications, and the exciting possibilities it holds for the future.",
        Understanding:
          "Virtual Reality Virtual Reality refers to a simulated experience that can be similar to or entirely different from the real world. It is typically generated by computer technology and experienced through sensory perceptions such as sight, sound, touch, and even smell in some advanced systems. The primary goal of VR is to immerse users in a synthetic environment, blurring the line between what is real and what is computer-generated.",
        A_Brief_History: `The concept of VR has been around for decades, with early experiments dating back to the 1960s. However, it wasn't until the 21st century that VR technology began to gain significant traction. Key milestones include the development of the Oculus Rift headset in 2012 and the subsequent acquisition of Oculus by Facebook (now Meta) in 2014, which injected substantial resources into VR development.`,
        The_Future: `The future of VR is bright, with ongoing advancements in hardware and software pushing the boundaries of what is possible `,
        Conclusion: `Virtual Reality is no longer science fiction; it's a transformative technology with a growing impact on our lives. As VR continues to evolve, it will touch virtually every aspect of our daily routines, from entertainment and education to healthcare and beyond. As we journey deeper into this immersive world, one thing is clear: Virtual Reality is here to stay, and the possibilities are virtually endless.`,
      },
    },
  },
  {
    id: 9,
    data: {
      name: "Web Design For Kids",
      short: "Web Design",
      about:
        "Teaching web design to kids can be a fun and creative way to introduce them to technology and design principles.",
      levels: "4",
      hours: "32",
      imgName: "web.jpeg",
      course_info: {
        info: "In recent years, Virtual Reality (VR) has transitioned from a futuristic concept into a tangible and transformative technology that is changing the way we interact with the digital world. This article delves into the world of VR, exploring its origins, current applications, and the exciting possibilities it holds for the future.",
        Understanding:
          "Virtual Reality Virtual Reality refers to a simulated experience that can be similar to or entirely different from the real world. It is typically generated by computer technology and experienced through sensory perceptions such as sight, sound, touch, and even smell in some advanced systems. The primary goal of VR is to immerse users in a synthetic environment, blurring the line between what is real and what is computer-generated.",
        A_Brief_History: `The concept of VR has been around for decades, with early experiments dating back to the 1960s. However, it wasn't until the 21st century that VR technology began to gain significant traction. Key milestones include the development of the Oculus Rift headset in 2012 and the subsequent acquisition of Oculus by Facebook (now Meta) in 2014, which injected substantial resources into VR development.`,
        The_Future: `The future of VR is bright, with ongoing advancements in hardware and software pushing the boundaries of what is possible `,
        Conclusion: `Virtual Reality is no longer science fiction; it's a transformative technology with a growing impact on our lives. As VR continues to evolve, it will touch virtually every aspect of our daily routines, from entertainment and education to healthcare and beyond. As we journey deeper into this immersive world, one thing is clear: Virtual Reality is here to stay, and the possibilities are virtually endless.`,
      },
    },
  },
];

export default Courses;
